version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-23-121.compute-1.amazonaws.com
            database: d3s0tqc3cmo693
            user: ttfmpgrmeojfcz
            password: 442cf64fb029cf06acb0398d6411b04f0b61f14c01a2dc10ef6a85492a9a245e
            rawAccess: true
            port: '5432'
            migrations: true
            ssl: true
